import { db } from "@/db";
import { videos } from "@/db/schema";
import { serve } from "@upstash/workflow/nextjs";
import { and, eq } from "drizzle-orm";

interface InputType {
  userId: string;
  videoId: string;
}

const TITLE_SYSTEM_PROMPT = `Your task is to generate an SEO-focused title for a YouTube video based on its transcript. Please follow these guidelines:
- Be concise but descriptive, using relevant keywords to improve discoverability.
- Highlight the most compelling or unique aspect of the video content.
- Avoid jargon or overly complex language unless it directly supports searchability.
- Use action-oriented phrasing or clear value propositions where applicable.
- Ensure the title is 3-8 words long and no more than 100 characters.
- ONLY return the title as plain text. Do not add quotes or any additional formatting.`;

export const { POST } = serve(async (context) => {
  const input = context.requestPayload as InputType;
  const { videoId, userId } = input;

  const video = await context.run("get-video", async () => {
    const [existingVideo] = await db
      .select()
      .from(videos)
      .where(
        and(eq(videos.id, videoId), eq(videos.userId, userId))
      );

    if (!existingVideo) {
      throw new Error("Not found");
    }

    return existingVideo;
  });
  //get transcript
  const transcript=await context.run("get-transcript",async()=>{
    //https://www.mux.com/docs/guides/add-autogenerated-captions-and-use-transcripts#retrieving-a-transcript
    const trackUrl=`https://stream.mux.com/${video.muxPlaybackId}/text/${video.muxTrackId}.txt`;
    const response =await fetch(trackUrl);
    const text=response.text();
    if(!text){
      throw new Error("Bad request")
    }
    return text;
  })
   
  const token = process.env.DEEPSEEK_API_KEY;
  if (!token) throw new Error("Missing DeepSeek API key");

  const response = await fetch("https://api.deepseek.com/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify({
      model: "deepseek-chat",
      messages: [
        {
          role: "system",
          content: TITLE_SYSTEM_PROMPT,
        },
        {
          role: "user",
          content: transcript,
        },
      ],
      stream: false,
    }),
  });

  if (!response.ok) {
    throw new Error(`DeepSeek API request failed with status ${response.status}`);
  }

  const data = await response.json();
  const title = data.choices[0]?.message?.content?.trim();
    if(!title){
      throw new Error("Bad request");
    }
  await context.run("update-video", async () => {
    await db
      .update(videos)
      .set({
        title: title || video.title,
      })
      .where(
        and(eq(videos.id, video.id),
           eq(videos.userId, video.userId)
           )
      );
  });
});
