import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ClerkProvider}from '@clerk/nextjs';
import { TRPCProvider } from "@/trpc/client";
const inter=Inter({
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl='/'>
    <html lang="en">
      <body
      // inter.className itself is a string ,so we don't need template literal here,but like inter.variable ,this is a JS express not a string, we need to use template literal to wrap it.
        className={inter.className}
      >
        {/* 让子组件访问 tRPC 的服务和数据。 */}
        <TRPCProvider>
        {children}
        </TRPCProvider>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
